djangogramm/app/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns


from . import views

app_name = 'app'
urlpatterns = [
    path('', views.Authentication.as_view(), name='handle_authentication'),
    path('register', views.Register.as_view(), name='register'),
    path('logout', views.logout_view, name='logout'),
    path('<int:pk>/enter_info', views.UserEnterInfoView.as_view(), name='enter_info'),
    path('<int:pk>/edit_profile', views.UserEditInfoView.as_view(), name='edit_profile'),
    path('<int:pk>/change_avatar', views.UserAvatarUpdateView.as_view(), name='change_avatar'),
    path('<int:pk>/add_post', views.AddPostView.as_view(), name='add_post'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('<int:pk>/profile', views.UserProfile.as_view(), name='profile'),
    path('p/<int:pk>', views.PostDetail.as_view(), name='post_detail'),
    path('p/<int:pk>/delete', views.PostDeleteView.as_view(), name='post_delete'),
    path('p/<int:pk>/update', views.PostUpdateView.as_view(), name='post_update'),
    path('feed', views.Feed.as_view(), name='feed'),
    path('subscriptions/<int:follower_id>', views.SubscriptionList.as_view(), name='subscription_list'),
    path('subscriptions/<int:follower_id>/<int:followee_id>', views.SubscriptionDetail.as_view(), name='subscription'),
    path('explore', views.ExploreUserListView.as_view(), name='user-list'),
    path('likes/<int:post_id>', views.LikeList.as_view(), name='likes'),
    path('likes/<int:post_id>/<int:user_id>', views.LikeDetail.as_view(), name='like'),
    path('user/<int:pk>/fullname', views.UserInfoAPI.as_view(), name='user_fullname'),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += format_suffix_patterns([path('posts/', views.UserPostList.as_view(), name='posts')])

djangogramm/djangogramm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangogramm/app/models.py
import os

from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.urls import reverse
from PIL import Image
from cloudinary.models import CloudinaryField as BaseCloudinaryField

EMPTY_USER_IMAGE = os.getenv('EMPTY_USER_IMAGE')


class CloudinaryAvatarField(BaseCloudinaryField):
    def upload_options(self, instance):
        return {
            'folder': f"media/{instance.id}/avatar/",
            'public_id': f"avatar_{instance.id}",
        }

    def pre_save(self, model_instance, add):
        self.options.update(self.upload_options(model_instance))
        return super().pre_save(model_instance, add)


class CloudinaryPostField(BaseCloudinaryField):
    def upload_options(self, instance):
        print(instance.pub_date)
        return {
            'folder': f"media/{instance.user.id}/posts/",
            'public_id': f"{instance.user.id}_{instance.pub_date}",
        }

    def pre_save(self, model_instance, add):
        self.options.update(self.upload_options(model_instance))
        return super().pre_save(model_instance, add)


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None, **kwargs):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(email=self.normalize_email(email))

        user.set_password(password)
        if kwargs.get('is_active') is True:
            user.is_active = True
        if isinstance(kwargs.get('first_name'), str):
            user.first_name = kwargs.get('first_name')
        if isinstance(kwargs.get('last_name'), str):
            user.last_name = kwargs.get('last_name')
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


def user_avatar_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/avatar/<filename>
    return f'{instance.id}/avatar/{filename}'


def user_posts_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/posts/<filename>
    return f'{instance.user.id}/posts/{filename}'


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    first_name = models.CharField(blank=True, max_length=20)
    last_name = models.CharField(blank=True, max_length=20)
    bio = models.TextField(blank=True, max_length=70)
    avatar = CloudinaryAvatarField('image', default=EMPTY_USER_IMAGE, proxy='http://proxy.server:3128')
    followers = models.ManyToManyField('self', through='Subscription', through_fields=('followee', 'follower'))
    following = models.ManyToManyField('self', through='Subscription', through_fields=('follower', 'followee'))

    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    # code for Pillow, before using Cloudinary
    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)  # saving image first
    #     if self.avatar:
    #         with Image.open(self.avatar.path) as img:
    #             if img.height > 512 or img.width > 512:
    #                 size = (512, 512)
    #                 img.thumbnail(size)
    #                 img.save(self.avatar.path, format="JPEG")  # saving image at the same path

    @property
    def is_staff(self):
        return self.is_admin


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    caption = models.CharField(max_length=200, blank=True)
    pub_date = models.DateTimeField('date posted', auto_now_add=True)
    likes = models.ManyToManyField(User, through='Like', related_name='users_liked')
    image = CloudinaryPostField('image', proxy='http://proxy.server:3128')

    class Meta:
        ordering = ['-pub_date']

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # Call the "real" save() method.

    # def save(self):
    #     super().save()  # saving image first
    #     if self.image:
    #         with Image.open(self.image.path) as img:
    #             if img.height > 1024 or img.width > 1024:
    #                 size = (1024, 1024)
    #                 img.thumbnail(size)
    #                 img.save(self.image.path, format="JPEG")  # saving image at the same path

    def get_absolute_url(self):
        return reverse('app:post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.id} {self.user}: (caption: {self.caption}, date: {self.pub_date})"


class Subscription(models.Model):
    followee = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subscription_followees')
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subscription_followers')

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['followee', 'follower'], name='unique_subscription'),
            models.CheckConstraint(check=~models.Q(followee=models.F('follower')),
                                   name='followee_and_follower_cannot_be_equal')
        ]

    def __repr__(self):
        return f"{self.__class__.__name__}({self.followee}, {self.follower})"

    def __str__(self):
        return f"{self.followee} is followed by {self.follower}"


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['post', 'user'], name='only_one_like_from_user'),
        ]

    def __repr__(self):
        return f"{self.__class__.__name__}({self.post}, {self.user})"

    def __str__(self):
        return f"User {self.user.id} liked Post {self.post.id}"

djangogramm/app/templates/app/base_navbar.html
{% extends "app/base.html" %}

{% block head %}
<script src="https://kit.fontawesome.com/9822aa20bd.js" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}
<div class="container">
    <nav class="navbar navbar-expand sticky-top navbar-light mb-4 mt-2 bg-white border-bottom">
        <a class="navbar-brand display-4 ms-3" href="{% url 'app:feed' %}">DjangoGramm</a>
        <ul class="navbar-nav">
            <li class="nav-item ps-sm-2">
                <a href="{% url 'app:user-list' %}"
                   style="color: gray; text-decoration: underline">
                explore
                </a>
            </li>
        </ul>
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'app:feed' %}">
                    <span style="font-size: 1.5em; color: #0d6efd;">
                        <i class="fas fa-home"></i>
                    </span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'app:add_post' auth_user.id %}">
                    <span style="font-size: 1.5em; color: #0d6efd;">
                        <i class="far fa-plus-square"></i>
                    </span>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <span style="font-size: 1.5em; color: #0d6efd;">
                        <i class="far fa-user-circle"></i>
                    </span>
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'app:profile' auth_user.id %}">Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'app:edit_profile' auth_user.id %}">Edit profile</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'app:logout' %}">Sign out</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div class="row">{% block below-navbar %}{% endblock %}</div>
    <div class="row">{% block second-row %}{% endblock %}</div>
</div>
{% endblock %}

djangogramm/app/templates/app/post_detail.html
{% extends "app/base_navbar.html" %}

{% block head %}
{% load static %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'app/css/post_detail.css' %}">
{{ block.super }}
{% load cloudinary %}
{% endblock %}

{% block below-navbar %}
<div class="col d-flex flex-column mx-auto mb-5 align-items-center">
    <div class="post">
        <div class="card mb-4" style="border-radius: 10px;">
            <div class="post-user">
                <div class="avatar">
                    <a href="{% url 'app:profile' post.user.id %}">
                        {% cloudinary post.user.avatar format="jpg" alt="avatar" %}
                    </a>
                </div>
                <div class="author">
                    <a href="{% url 'app:profile' post.user.id %}">
                        {{ post.user.first_name }} {{ post.user.last_name }}
                    </a>
                </div>
            </div>
            <div class="post-image">{% cloudinary post.image format="jpg" alt="post" %}</div>
            <div class="like-container d-flex mt-3 ms-3">
                <div class="heart d-flex align-items-center" id="heart"><i></i></div>
                <div class="number-likes ps-2 d-flex align-items-center" data-bs-toggle="modal" data-bs-target="#likesModal">
                    {% with total=post.likes.count %}
                        <span id="num-likes" class="me-1">{{ total }}</span>
                        <span id="like-word">like{{ total|pluralize }}</span>
                    {% endwith %}
                </div>
            </div>
            <div class="caption mx-3 mt-3">
                <p>
                    <span class="author">
                        <a href="{% url 'app:profile' post.user.id %}">
                            {{ post.user.first_name }} {{ post.user.last_name }}
                        </a>
                    </span>
                    {{ post.caption }}
                </p>
            </div>
            <div class="date ms-3 my-3">
                <p>{{ post_timedelta }}</p>
            </div>
        </div>
        {% if can_edit %}
        <div class="row gx-2">
            <div class="col-6">
                <button class="btn btn-danger btn-lg w-100 fw-bold fs-6" id="delete-btn" type="button"
                        data-bs-toggle="modal" data-bs-target="#deleteModal">
                    Delete
                </button>
            </div>
            <div class="col-6">
                <button class="btn btn-primary btn-lg w-100 fw-bold fs-6" id="edit-btn" type="button"
                        data-bs-toggle="modal" data-bs-target="#editModal">
                    Edit
                </button>
            </div>
        </div>
        {% endif %}
    </div>
</div>

<!-- Modal Delete -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content" style="border-radius: 12px;">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete post</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this post?
            </div>
            <div class="modal-footer" style="border-top: none">
                <form method="post" action="{% url 'app:post_delete' post.id %}">{% csrf_token %}
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger">Confirm</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal Edit -->
<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content" style="border-radius: 12px;">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Edit post</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" action="{% url 'app:post_update' post.id %}">{% csrf_token %}
                <div class="modal-body">
                    <label for="id_caption" class="form-label">Caption:</label>
                    <textarea class="form-control" name="caption" maxlength="200" id="id_caption"
                              rows="4">{{ post.caption }}</textarea>
                </div>
                <div class="modal-footer" style="border-top: none;">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>


<!-- Likes Modal -->
<div class="modal fade" id="likesModal" tabindex="-1" aria-labelledby="likesModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="likesModalLabel">Likes</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <ul class="ppl-liked">
                    {% for person in post.likes.all %}
                    <li>
                        <div class="person-liked">
                            <a href="{% url 'app:profile' person.id %}">
                                {% cloudinary person.avatar format="jpg" alt="avatar" %}
                            </a>
                            <a href="{% url 'app:profile' person.id %}">
                                <span class="name ms-2">{{ person.first_name }} {{ person.last_name }}</span>
                            </a>
                        </div>
                    </li>
                    {% empty %}
                        <li>No likes yet</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block script %}
{{ liked|json_script:"liked" }}
{{ post.id|json_script:"postId" }}
{{ auth_user.id|json_script:"userId" }}
<script src="{% static 'app/js/post_detail.js' %}"></script>
{% endblock %}

djangogramm/app/templates/app/user_detail.html
{% extends "app/base_navbar.html" %}
{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/user_detail.css' %}">
{% load cloudinary %}
{{ block.super }}
{% endblock %}

{% block below-navbar %}
<div class="col-4">
    <div class="py-5 d-flex flex-row justify-content-center">
        {% if can_edit %}
            {% if empty_avatar %}
                <label for="id_avatar">
                    {% cloudinary user.avatar format="jpg" class="avatar-img avatar-can-change" alt="avatar here" %}
                </label>
                <form method="post" enctype="multipart/form-data" id="form_empty_img"
                      action="{% url 'app:change_avatar' auth_user.id %}">
                    {% csrf_token %}
                    <input type="file" name="avatar" accept="image/*" id="id_avatar" style="display: none;">
                </form>
            {% else %}
                <div data-bs-toggle="modal" data-bs-target="#editAvatarModal">
                    {% cloudinary user.avatar format="jpg" class="avatar-img avatar-can-change" alt="avatar here" %}
                </div>
            {% endif %}
        {% else %}
            {% cloudinary user.avatar format="jpg" class="avatar-img" alt="avatar here" %}
        {% endif %}
    </div>
</div>
<div class="col-8">
    <h3 class="display-6 mb-4">{{ user.first_name }} {{ user.last_name }}</h3>
    <div class="d-flex flex-row mb-4 stats">
        <div class="user-info">
            <p class="amount">{{ num_posts }}</p>
            {% if num_posts == 1 %}
                <p>Post</p>
            {% else %}
                <p>Posts</p>
            {% endif %}
        </div>
        <div class="mx-3 mx-md-5 user-info" data-bs-toggle="modal" data-bs-target="#followersModal">
            {% with total=followers|length %}
                <p class="amount" id="num-followers">{{ total }}</p>
                <p id="id-followers">Follower{{ total|pluralize }}</p>
            {% endwith %}
        </div>
        <div class="user-info" data-bs-toggle="modal" data-bs-target="#followingModal">
            <p class="amount">{{ following|length }}</p>
            <p>Following</p>
        </div>
    </div>
    <p class="text-wrap" id="bio">{{ user.bio }}</p>
</div>

<!-- Modal Edit Avatar-->
<div class="modal fade" id="editAvatarModal" tabindex="-1" aria-labelledby="editAvatarModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content" style="border-radius: 12px;">
            <div class="modal-header d-flex flex-column align-items-center">
                <h5 class="modal-title" id="editAvatarModalLabel">Change Profile Photo</h5>
            </div>
            <div class="modal-body d-flex flex-column" style="padding: 0;">
                <label for="id_avatar_nonempty">
                    <div class="border-bottom py-3 text-primary fw-bold" style="text-align: center; cursor: pointer;">
                        Upload Photo
                    </div>
                </label>
                <form method="post" enctype="multipart/form-data" id="form_nonempty_img" class="border-bottom py-3"
                      action="{% url 'app:change_avatar' auth_user.id %}" style="text-align: center;">
                    {% csrf_token %}
                    <input type="file" name="avatar" accept="image/*" id="id_avatar_nonempty" style="display: none;">
                    <button type="submit" class="text-danger fw-bold" name="delete_avatar"
                            value="true" style="background: none; border: none;">
                        Remove Current Photo
                    </button>
                </form>
                <button type="button" class="py-3 cancel-modal" data-bs-dismiss="modal">
                    Cancel
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Confirm Unfollow-->
<div class="modal fade" id="unfollowModal" tabindex="-1" aria-labelledby="unfollowModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content" style="border-radius: 12px;">
            <div class="modal-header d-flex flex-column align-items-center">
                <h5 class="modal-title" id="unfollowModalLabel">
                    Unfollow {{ user.first_name }} {{ user.last_name }}?
                </h5>
            </div>
            <div class="modal-body d-flex flex-column" style="padding: 0;">
                <button type="button" id='confirm-unfollow' class="border-bottom py-3 text-danger fw-bold"
                        data-bs-dismiss="modal">
                    Unfollow
                </button>
                <button type="button" class="py-3 cancel-modal" data-bs-dismiss="modal">
                    Cancel
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Followers Modal -->
<div class="modal fade" id="followersModal" tabindex="-1" aria-labelledby="followersModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="followersModalLabel">Followers</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <ul class="followers">
                    {% for follower in user.followers.all %}
                    <li>
                        <div class="follower">
                            <a href="{% url 'app:profile' follower.id %}">
                                {% cloudinary follower.avatar format="jpg" alt="avatar" %}
                            </a>
                            <a href="{% url 'app:profile' follower.id %}">
                                <span class="name ms-2">{{ follower.first_name }} {{ follower.last_name }}</span>
                            </a>
                        </div>
                    </li>
                    {% empty %}
                        <li>You don't have followers</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>


<!-- Following Modal -->
<div class="modal fade" id="followingModal" tabindex="-1" aria-labelledby="followingModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="followingModalLabel">Following</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <ul class="followees">
                    {% for followee in user.following.all %}
                    <li>
                        <div class="followee">
                            <a href="{% url 'app:profile' followee.id %}">
                                {% cloudinary followee.avatar format="jpg" alt="avatar" %}
                            </a>
                            <a href="{% url 'app:profile' followee.id %}">
                                <span class="name ms-2">{{ followee.first_name }} {{ followee.last_name }}</span>
                            </a>
                        </div>
                    </li>
                    {% empty %}
                        <li>You don't follow anyone yet</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block second-row %}
<div class="user_posts"></div>
{% endblock %}

{% block script %}
{{ follow_params|json_script:"follow-data" }}
{{ auth_user.id|json_script:"auth-user-id" }}
<script src="{% static 'app/js/profile_page.js' %}" user_id={{ user.id }} post_count={{ user.post_set.count }}>
</script>
<script>
    if (document.getElementById("id_avatar")) {
        document.getElementById("id_avatar").onchange = function() {
            document.getElementById("form_empty_img").submit();
        };
    };
    document.getElementById("id_avatar_nonempty").onchange = function() {
        document.getElementById("form_nonempty_img").submit();
    };
</script>
{% endblock %}

djangogramm/app/templates/app/user_edit_profile.html
{% extends "app/base_navbar.html" %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/user_edit_profile.css' %}">
{{ block.super }}
{% load cloudinary %}
{% endblock %}

{% block below-navbar %}
<div class="col d-flex flex-column align-items-center mx-auto mb-5">
    <div class="mb-3"><h3>Edit Profile</h3></div>
    <form enctype="multipart/form-data" action="{% url 'app:edit_profile' user.id %}"  method="POST" class="w-100" style="max-width: 420px">
        {% csrf_token %}
        <div class="mb-4 text-center">
            <div class="mb-3">
                <label>
                    {{ form.avatar }}
                    {% cloudinary user.avatar format="jpg" id="output" alt="avatar here" %}
                </label>
            </div>
            <div>
                <label>
                    {{ form.avatar }}
                    <a class="upload">Upload photo</a>
                </label>
            </div>
        </div>
        <div class="mb-3">
            <label for="id_first_name" class="form-label">First Name</label>
            {{ form.first_name }}
        </div>
        <div class="mb-3">
            <label for="id_last_name" class="form-label">Last Name</label>
            {{ form.last_name }}
        </div>
        <div class="mb-5">
            <label for="id_bio" class="form-label">Bio</label>
            {{ form.bio }}
        </div>
        <div class="row gx-2">
            <div class="col-6">
                <button class="btn btn-secondary btn-lg w-100 fw-bold fs-6" id="cancel-btn" type="button" onclick="location.href=`{% url 'app:profile' user.id %}`">
                    Cancel
                </button>
            </div>
            <div class="col-6">
                <button class="btn btn-primary btn-lg w-100 fw-bold fs-6" id="submit-btn" type="submit">
                    Submit
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block script %}
<script>
    var loadFile = function(event) {
        var output = document.getElementById('output');
        output.src = URL.createObjectURL(event.target.files[0]);
        output.onload = function() {
            URL.revokeObjectURL(output.src) // free memory
        }
    };
</script>
{% endblock %}

djangogramm/app/templates/app/user_enter_info.html
{% extends "app/base.html" %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/css/login_register.css' %}">
<script src="https://kit.fontawesome.com/9822aa20bd.js" crossorigin="anonymous"></script>
{% load cloudinary %}
{% endblock %}

{% block content %}
 <div class="container mt-2">
    <div class="row min-vh-100">
        <div class="col-12 col-md-5 col-xl-7 d-flex flex-column justify-content-center align-items-center">
            <div class="d-flex flex-column">
                <h1 class="display-4">Welcome to</h1>
                <h1 class="display-4 mb-5">DjangoGramm</h1>
                <h4 class="text-wrap">Please enter some basic info about you</h4>
                <div class="mb-5"><span class="link">{{ user.email }}</span></div>
            </div>
        </div>
        <div class="col-12 col-md-7 col-xl-5 d-flex flex-column justify-content-center align-items-center">

            <form enctype="multipart/form-data" action="{% url 'app:enter_info' user.id %}"
                  method="POST" class="w-75" style="max-width: 500px">
                {% csrf_token %}
                <div class="mb-4 text-center">
                    <div class="mb-3">
                        <label>
                            {{ form.avatar }}
                            <img id="output" src="{% static 'app/img/empty_user.jpg' %}">
                        </label>
                    </div>
                    <div>
                        <label>
                            {{ form.avatar }}
                            <a class="sign-out">Upload photo</a>
                        </label>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="id_first_name" class="form-label">First Name</label>
                    {{ form.first_name }}
                </div>
                <div class="mb-3">
                    <label for="id_last_name" class="form-label">Last Name</label>
                    {{ form.last_name }}
                </div>
                <div class="mb-5">
                    <label for="id_bio" class="form-label">Bio</label>
                    {{ form.bio }}
                </div>
                <button class="btn btn-primary btn-lg w-100 fw-bold fs-6 mb-4" id="action-btn"
                        name="proceed" type="submit" value="continue">
                    Continue
                </button>
                <div class="w-100 mb-5" style="text-align: right;">
                    <a href="{% url 'app:logout'%}" class="sign-out">
                        <i class="fas fa-sign-out-alt" style="color: #0d6efd;"></i> Sign out
                    </a>
                </div>
            </form>
        </div>
    </div>
 </div>
{% endblock %}

{% block script %}
<script>
    var loadFile = function(event) {
        var output = document.getElementById('output');
        output.src = URL.createObjectURL(event.target.files[0]);
        output.onload = function() {
          URL.revokeObjectURL(output.src) // free memory
        }
    };
</script>
{% endblock %}